version: '3.1'
services:

  nest:
    container_name: nest-server
    image: nest-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - study-group-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - study-group-network

networks:
  study-group-network:
    driver: bridge

